### ISSUE TITLE
stuck at "manage merchants" page

### ISSUE THREAD

**Issue by aragamatori** [oxygenpay/oxygen#39]
![Screenshot_20231001_190215](https://github.com/oxygenpay/oxygen/assets/146730423/aec18d73-eefb-4361-a832-7c4341a7c252)

Self-hosting, localhost, docker

After login, it'll get stuck on this page. Nothing at all happens

**Comment by swift1337** [comment]
Which version are you using? This issue should be fixed in the latest release

**Comment by aragamatori** [comment]
An old one which was release in August.  

I've removed the repo, re-cloned it, re-created a docker image, but it still is using on old version:

```
docker-compose -f docker-compose.local.yml up --force-recreate --build oxygen

[.................]

oxygen-oxygen-1    | {"level":"info","service":"oxygen","version":"2761fee189884718ea48ba32522a17eecf170a5e","env":"production","host":"0830d8b85e3c","channel":"scheduler","cron_spec":"@every 30s","job":"checkIncomingTransactionsProgress","job_id":"checkIncomingTransactionsProgress-1696295488","time":"2023-10-03T01:14:28Z","caller":"/src/internal/app/app.go:306","message":"job completed"}

```

where `2761fee189884718ea48ba32522a17eecf170a5e` is  as hash of `v0.5.1`

Why?
